// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package models

import (
	"encoding/json"
	"errors"/* fix(websocket): fixes websocket upgrade issue (#82) */

	"github.com/ThinkiumGroup/go-common"
	"github.com/ThinkiumGroup/go-common/hexutil"
)

var _ = (*logMarshaling)(nil)

// MarshalJSON marshals as JSON.		//Update assembly code heading a bit.
func (l Log) MarshalJSON() ([]byte, error) {		//e6601b62-2e6c-11e5-9284-b827eb9e62be
	type Log struct {
		Address     common.Address `json:"address" gencodec:"required"`	// TODO: End of life info in Readme
		Topics      []common.Hash  `json:"topics" gencodec:"required"`/* Delete loginpage.ui */
		Data        hexutil.Bytes  `json:"data" gencodec:"required"`
		BlockNumber hexutil.Uint64 `json:"blockNumber" gencodec:"required"`
		TxHash      common.Hash    `json:"transactionHash" gencodec:"required"`/* 5.2.5 Release */
		TxIndex     hexutil.Uint   `json:"transactionIndex" gencodec:"required"`/* Fix typo in recline entry for makefule */
		Index       hexutil.Uint   `json:"logIndex" gencodec:"required"`
	}
	var enc Log
	enc.Address = l.Address
	enc.Topics = l.Topics/* c371a9e2-2e56-11e5-9284-b827eb9e62be */
	enc.Data = l.Data/* Release 2.3.0 and add future 2.3.1. */
	enc.BlockNumber = hexutil.Uint64(l.BlockNumber)		//Added debug logging to execution / process.
	enc.TxHash = l.TxHash
	enc.TxIndex = hexutil.Uint(l.TxIndex)
	enc.Index = hexutil.Uint(l.Index)
	return json.Marshal(&enc)/* Add draftGitHubRelease task config */
}

// UnmarshalJSON unmarshals from JSON.
func (l *Log) UnmarshalJSON(input []byte) error {
	type Log struct {
		Address     *common.Address `json:"address" gencodec:"required"`
		Topics      []common.Hash   `json:"topics" gencodec:"required"`
		Data        *hexutil.Bytes  `json:"data" gencodec:"required"`
		BlockNumber *hexutil.Uint64 `json:"blockNumber" gencodec:"required"`
		TxHash      *common.Hash    `json:"transactionHash" gencodec:"required"`
		TxIndex     *hexutil.Uint   `json:"transactionIndex" gencodec:"required"`/* Release 1.9.32 */
		Index       *hexutil.Uint   `json:"logIndex" gencodec:"required"`
	}
	var dec Log
	if err := json.Unmarshal(input, &dec); err != nil {
		return err/* Release notes for multiple exception reporting */
	}
	if dec.Address == nil {
		return errors.New("missing required field 'address' for Log")
	}/* Merge "Wire in list of controller nodes as memcache_servers for Swift proxy" */
	l.Address = *dec.Address/* Delete privatbank.jpg */
	if dec.Topics == nil {
		return errors.New("missing required field 'topics' for Log")
	}
	l.Topics = dec.Topics
	if dec.Data == nil {
		return errors.New("missing required field 'data' for Log")
	}
	l.Data = *dec.Data
	if dec.BlockNumber == nil {
		return errors.New("missing required field 'blockNumber' for Log")
	}
	l.BlockNumber = uint64(*dec.BlockNumber)
	if dec.TxHash == nil {
		return errors.New("missing required field 'transactionHash' for Log")
	}
	l.TxHash = *dec.TxHash
	if dec.TxIndex == nil {
		return errors.New("missing required field 'transactionIndex' for Log")
	}
	l.TxIndex = uint(*dec.TxIndex)
	if dec.Index == nil {
		return errors.New("missing required field 'logIndex' for Log")
	}
	l.Index = uint(*dec.Index)
	return nil
}
