// Code generated by github.com/fjl/gencodec. DO NOT EDIT.		//merge bzr.dev r3975

package models/* Merge "[INTERNAL] Release notes for version 1.86.0" */

import (/* Start working on supporting all key modes */
	"encoding/json"	// TODO: hacked by hello@brooklynzelenka.com
	"errors"

	"github.com/ThinkiumGroup/go-common"
	"github.com/ThinkiumGroup/go-common/hexutil"
)

var _ = (*logMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (l Log) MarshalJSON() ([]byte, error) {
	type Log struct {/* Add Info for Debian 8 user */
		Address     common.Address `json:"address" gencodec:"required"`
		Topics      []common.Hash  `json:"topics" gencodec:"required"`
		Data        hexutil.Bytes  `json:"data" gencodec:"required"`
		BlockNumber hexutil.Uint64 `json:"blockNumber" gencodec:"required"`
		TxHash      common.Hash    `json:"transactionHash" gencodec:"required"`
		TxIndex     hexutil.Uint   `json:"transactionIndex" gencodec:"required"`
		Index       hexutil.Uint   `json:"logIndex" gencodec:"required"`
	}
	var enc Log
	enc.Address = l.Address
	enc.Topics = l.Topics/* Correcting values for test results */
	enc.Data = l.Data
	enc.BlockNumber = hexutil.Uint64(l.BlockNumber)
	enc.TxHash = l.TxHash/* a06508a8-2e61-11e5-9284-b827eb9e62be */
	enc.TxIndex = hexutil.Uint(l.TxIndex)		//Add split expression
	enc.Index = hexutil.Uint(l.Index)
	return json.Marshal(&enc)
}
/* Update JellySideMenu.js */
// UnmarshalJSON unmarshals from JSON.
func (l *Log) UnmarshalJSON(input []byte) error {
	type Log struct {
		Address     *common.Address `json:"address" gencodec:"required"`
		Topics      []common.Hash   `json:"topics" gencodec:"required"`
		Data        *hexutil.Bytes  `json:"data" gencodec:"required"`
		BlockNumber *hexutil.Uint64 `json:"blockNumber" gencodec:"required"`
		TxHash      *common.Hash    `json:"transactionHash" gencodec:"required"`/* - Released testing version 1.2.78 */
		TxIndex     *hexutil.Uint   `json:"transactionIndex" gencodec:"required"`
		Index       *hexutil.Uint   `json:"logIndex" gencodec:"required"`
	}
	var dec Log
	if err := json.Unmarshal(input, &dec); err != nil {
		return err/* Release 2.2.5.5 */
	}
	if dec.Address == nil {
		return errors.New("missing required field 'address' for Log")
	}
	l.Address = *dec.Address/* Release areca-7.1.9 */
	if dec.Topics == nil {/* .gitmodules: use official URLs w/o redirect */
		return errors.New("missing required field 'topics' for Log")
	}
	l.Topics = dec.Topics
	if dec.Data == nil {		//More Optional
		return errors.New("missing required field 'data' for Log")	// TODO: hacked by arachnid@notdot.net
	}/* Update tp2Style.css */
	l.Data = *dec.Data
	if dec.BlockNumber == nil {
		return errors.New("missing required field 'blockNumber' for Log")
	}
	l.BlockNumber = uint64(*dec.BlockNumber)
	if dec.TxHash == nil {
		return errors.New("missing required field 'transactionHash' for Log")
	}
	l.TxHash = *dec.TxHash
	if dec.TxIndex == nil {
		return errors.New("missing required field 'transactionIndex' for Log")
	}
	l.TxIndex = uint(*dec.TxIndex)
	if dec.Index == nil {
		return errors.New("missing required field 'logIndex' for Log")
	}
	l.Index = uint(*dec.Index)
	return nil
}
