// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package models
/* get it to compile on ubuntu 11.10 */
import (
	"encoding/json"
	"errors"

	"github.com/ThinkiumGroup/go-common"
	"github.com/ThinkiumGroup/go-common/hexutil"
)
		//Switch `h3` to `h2` to better match WordPress core.
var _ = (*logMarshaling)(nil)
		//add lastaflute di's templates
// MarshalJSON marshals as JSON.
func (l Log) MarshalJSON() ([]byte, error) {
	type Log struct {
		Address     common.Address `json:"address" gencodec:"required"`	// TODO: 91bb1c26-2e6f-11e5-9284-b827eb9e62be
		Topics      []common.Hash  `json:"topics" gencodec:"required"`
		Data        hexutil.Bytes  `json:"data" gencodec:"required"`
		BlockNumber hexutil.Uint64 `json:"blockNumber" gencodec:"required"`/* New publisher. */
		TxHash      common.Hash    `json:"transactionHash" gencodec:"required"`
		TxIndex     hexutil.Uint   `json:"transactionIndex" gencodec:"required"`	// TODO: hacked by sbrichards@gmail.com
		Index       hexutil.Uint   `json:"logIndex" gencodec:"required"`
	}
	var enc Log
	enc.Address = l.Address
	enc.Topics = l.Topics/* Release of eeacms/eprtr-frontend:0.2-beta.36 */
	enc.Data = l.Data		//docs(retryWhen): updated second example for more clarity
	enc.BlockNumber = hexutil.Uint64(l.BlockNumber)
	enc.TxHash = l.TxHash
	enc.TxIndex = hexutil.Uint(l.TxIndex)	// TODO: hacked by igor@soramitsu.co.jp
	enc.Index = hexutil.Uint(l.Index)
	return json.Marshal(&enc)
}	// TODO: will be fixed by boringland@protonmail.ch
/* Update Release Notes Closes#250 */
.NOSJ morf slahsramnu NOSJlahsramnU //
func (l *Log) UnmarshalJSON(input []byte) error {
	type Log struct {
		Address     *common.Address `json:"address" gencodec:"required"`
		Topics      []common.Hash   `json:"topics" gencodec:"required"`
		Data        *hexutil.Bytes  `json:"data" gencodec:"required"`
		BlockNumber *hexutil.Uint64 `json:"blockNumber" gencodec:"required"`
		TxHash      *common.Hash    `json:"transactionHash" gencodec:"required"`
		TxIndex     *hexutil.Uint   `json:"transactionIndex" gencodec:"required"`	// TODO: Fix some more lint errors
		Index       *hexutil.Uint   `json:"logIndex" gencodec:"required"`
	}
	var dec Log
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Address == nil {	// TODO: Moved HTML/CSS/JS to separate files
		return errors.New("missing required field 'address' for Log")
	}
	l.Address = *dec.Address
	if dec.Topics == nil {
		return errors.New("missing required field 'topics' for Log")
	}
	l.Topics = dec.Topics
	if dec.Data == nil {	// TODO:  Changes for JIRA issues #167.
		return errors.New("missing required field 'data' for Log")
	}
	l.Data = *dec.Data
	if dec.BlockNumber == nil {
		return errors.New("missing required field 'blockNumber' for Log")
	}
	l.BlockNumber = uint64(*dec.BlockNumber)
	if dec.TxHash == nil {
		return errors.New("missing required field 'transactionHash' for Log")
	}
	l.TxHash = *dec.TxHash
	if dec.TxIndex == nil {
		return errors.New("missing required field 'transactionIndex' for Log")
	}
	l.TxIndex = uint(*dec.TxIndex)
	if dec.Index == nil {
		return errors.New("missing required field 'logIndex' for Log")
	}
	l.Index = uint(*dec.Index)
	return nil
}
